---
- name: Create config directory
  ansible.builtin.file:
    path: "{{app_calibre_web_dir}}/config"
    state: directory
    owner: "{{app_calibre_web_puid}}"
    group: "{{app_calibre_web_pgid}}"
    mode: 0755

- name: Create books directory
  ansible.builtin.file:
    path: "{{app_calibre_web_dir}}/books"
    state: directory
    owner: "{{app_calibre_web_puid}}"
    group: "{{app_calibre_web_pgid}}"
    mode: 0755

- name: Ensure linuxserver/calibre-web image is pulled
  community.docker.docker_image:
    name: lscr.io/linuxserver/calibre-web
    source: pull
    force_source: yes
  register: pulled

- name: Remove calibre-web container
  community.docker.docker_container:
    name: calibre-web
    state: absent
  when: pulled.changed

- name: Get infos on calibre-web container
  community.docker.docker_container_info:
    name: calibre-web
  register: result

- name: Create calibre-web container
  ansible.builtin.shell: |
    docker run -d \
    --name=calibre-web \
    -e PUID={{app_calibre_web_puid}} \
    -e PGID={{app_calibre_web_pgid}} \
    -e TZ={{app_calibre_web_tz}} \
    -v /{{app_calibre_web_dir}}/config:/config:Z \
    -v /{{app_calibre_web_dir}}/books:/books:Z \
    --network=app-network \
    --restart unless-stopped \
    lscr.io/linuxserver/calibre-web
  when: 
    pulled.changed
    or
    result.exists == false
